In [1]:
import numpy as np

In [2]:
# error flag, for when things go wrong if the matrix is singular.
class SingularMatrix(Exception): pass

In [3]:
#function to go down the matrix and replace the numbers in each row and change to upper triangle form
#if it is unable to replace the number in diagonal to be one, return true, else return false
def isSingular(A) :
    #B is a local copy of the matix, as it value is going to be changed
    B = np.array(A, dtype=np.float_) 
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except SingularMatrix:
        return True
    return False

In [4]:
def fixRowZero(A) :
    # add the rows below row 0 to make sure it is not 0
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    # if element 1 for all rows are 0
    if A[0,0] == 0 :
        raise SingularMatrix()
    # set first element to be 1
    A[0] = A[0] / A[0,0] 
    return A

In [5]:
def fixRowOne(A) :
    # set the A[1,0] to zero as it is below the diagonal
    A[1] = A[1] - A[1,0] * A[0] 
    # add the rows below to make sure the number on the diagonal is not 0
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        # set elements below the diagonal to be zero
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        # set elements below the diagonal to be zero
        A[1] = A[1] - A[1,0] * A[0]
    # if element on the diagonal on this row are still 0
    if A[1,1] == 0 :
        raise SingularMatrix()
    # set the number on the diagonal to be 1
    A[1] = A[1] / A[1,1] 
    return A

In [6]:
def fixRowTwo(A) :
    # set the A[2,0]  and a[2,1] to zero as they are below the diagonal
    A[2] = A[2]-A[2,0]*A[0]
    A[2] = A[2]-A[2,1]*A[1]
    # add the rows below to make sure the number on the diagonal is not 0
    if A[2,2] == 0 :
        A[2] = A[2]+A[3]
        # set elements below the diagonal to be zero.
        A[2] = A[2]-A[2,0]*A[0]
        A[2] = A[2]-A[2,1]*A[1]
    # if element on the diagonal on this row are still 0
    if A[2,2] == 0 :
        raise SingularMatrix()
    # set the number on the diagonal to be 1
    A[2]=A[2]/A[2,2]
    return A

In [7]:
def fixRowThree(A) :
    # set elements below the diagonal to be zero.
    A[3] = A[3] - A[3,0]*A[0]
    A[3] = A[3] - A[3,1]*A[1]
    A[3] = A[3] - A[3,2]*A[2]
    # if element on the diagonal on this row are still 0
    if A[3,3] == 0:
        raise SingularMatrix()
    # set the number on the diagonal to be 1
    A[3]=A[3]/A[3,3]
    return A

<h1>Test</h1>

In [8]:
A = np.array([
        [3, 3, 0, 0],
        [0, 3, 3, 0],
        [0, 0, 7, 7],
        [0, 0, 2, 2]
    ], dtype=np.float_)
isSingular(A)

True

In [9]:
A = np.array([
        [3, 4, 5, -6],
        [0, 7, 8, 9],
        [0, 0, 2, 3],
        [0, 0, 2, 5]
    ], dtype=np.float_)
isSingular(A)

False

In [10]:
fixRowZero(A)

array([[ 1.        ,  1.33333333,  1.66666667, -2.        ],
       [ 0.        ,  7.        ,  8.        ,  9.        ],
       [ 0.        ,  0.        ,  2.        ,  3.        ],
       [ 0.        ,  0.        ,  2.        ,  5.        ]])

In [11]:
fixRowOne(A)

array([[ 1.        ,  1.33333333,  1.66666667, -2.        ],
       [ 0.        ,  1.        ,  1.14285714,  1.28571429],
       [ 0.        ,  0.        ,  2.        ,  3.        ],
       [ 0.        ,  0.        ,  2.        ,  5.        ]])

In [12]:
fixRowTwo(A)

array([[ 1.        ,  1.33333333,  1.66666667, -2.        ],
       [ 0.        ,  1.        ,  1.14285714,  1.28571429],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  2.        ,  5.        ]])

In [13]:
fixRowThree(A)

array([[ 1.        ,  1.33333333,  1.66666667, -2.        ],
       [ 0.        ,  1.        ,  1.14285714,  1.28571429],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])